version: '3'

services:
  redis:
    image: redis:5.0.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  boost-detector-backend:
    build: .
    restart: always
    environment:
    - REDIS_HOST=redis
    depends_on:
    - redis
    ports:
    - "80:8080"

volumes:
  redis-data:
