/**
* OpenDota API
* # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
*
* OpenAPI spec version: 17.6.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id id
 * @param name name
 * @param localized_name localized_name
 * @param img img
 * @param icon icon
 * @param pro_win pro_win
 * @param pro_pick pro_pick
 * @param hero_id The ID value of the hero played
 * @param pro_ban pro_ban
 * @param 1_pick Herald picks
 * @param 1_win Herald wins
 * @param 2_pick Guardian picks
 * @param 2_win Guardian wins
 * @param 3_pick Crusader picks
 * @param 3_win Crusader wins
 * @param 4_pick Archon picks
 * @param 4_win Archon wins
 * @param 5_pick Legend picks
 * @param 5_win Legend wins
 * @param 6_pick Ancient picks
 * @param 6_win Ancient wins
 * @param 7_pick Divine picks
 * @param 7_win Divine wins
 */
data class Inline_response_200_22 (
    /* id */
    val id: kotlin.Int? = null,
    /* name */
    val name: kotlin.String? = null,
    /* localized_name */
    val localized_name: kotlin.String? = null,
    /* img */
    val img: kotlin.String? = null,
    /* icon */
    val icon: kotlin.String? = null,
    /* pro_win */
    val pro_win: kotlin.Int? = null,
    /* pro_pick */
    val pro_pick: kotlin.Int? = null,
    /* The ID value of the hero played */
    val hero_id: kotlin.Int? = null,
    /* pro_ban */
    val pro_ban: kotlin.Int? = null
    /* Herald picks */
//    val 1_pick: kotlin.Int? = null,
//    /* Herald wins */
//    val 1_win: kotlin.Int? = null,
//    /* Guardian picks */
//    val 2_pick: kotlin.Int? = null,
//    /* Guardian wins */
//    val 2_win: kotlin.Int? = null,
//    /* Crusader picks */
//    val 3_pick: kotlin.Int? = null,
//    /* Crusader wins */
//    val 3_win: kotlin.Int? = null,
//    /* Archon picks */
//    val 4_pick: kotlin.Int? = null,
//    /* Archon wins */
//    val 4_win: kotlin.Int? = null,
//    /* Legend picks */
//    val 5_pick: kotlin.Int? = null,
//    /* Legend wins */
//    val 5_win: kotlin.Int? = null,
//    /* Ancient picks */
//    val 6_pick: kotlin.Int? = null,
//    /* Ancient wins */
//    val 6_win: kotlin.Int? = null,
//    /* Divine picks */
//    val 7_pick: kotlin.Int? = null,
//    /* Divine wins */
//    val 7_win: kotlin.Int? = null
) {

}

