/**
* OpenDota API
* # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
*
* OpenAPI spec version: 17.6.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * profile
 * @param account_id account_id
 * @param personaname personaname
 * @param name name
 * @param cheese cheese
 * @param steamid steamid
 * @param avatar avatar
 * @param avatarmedium avatarmedium
 * @param avatarfull avatarfull
 * @param profileurl profileurl
 * @param last_login last_login
 * @param loccountrycode loccountrycode
 * @param is_contributor Boolean indicating if the user contributed to the development of OpenDota
 */
data class Inline_response_200_1_profile (
    /* account_id */
    val account_id: kotlin.Int? = null,
    /* personaname */
    val personaname: kotlin.String? = null,
    /* name */
    val name: kotlin.String? = null,
    /* cheese */
    val cheese: kotlin.Int? = null,
    /* steamid */
    val steamid: kotlin.String? = null,
    /* avatar */
    val avatar: kotlin.String? = null,
    /* avatarmedium */
    val avatarmedium: kotlin.String? = null,
    /* avatarfull */
    val avatarfull: kotlin.String? = null,
    /* profileurl */
    val profileurl: kotlin.String? = null,
    /* last_login */
    val last_login: kotlin.String? = null,
    /* loccountrycode */
    val loccountrycode: kotlin.String? = null,
    /* Boolean indicating if the user contributed to the development of OpenDota */
    val is_contributor: kotlin.Boolean? = null
) {

}

