/**
* OpenDota API
* # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
*
* OpenAPI spec version: 17.6.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.apis

import io.swagger.client.models.Inline_response_200_15

import io.swagger.client.infrastructure.*

class PublicMatchesApi(basePath: kotlin.String = "https://api.opendota.com/api") : ApiClient(basePath) {

    /**
    * GET /publicMatches
    * Get list of randomly sampled public matches
    * @param mmrAscending Order by MMR ascending (optional)
    * @param mmrDescending Order by MMR descending (optional)
    * @param lessThanMatchId Get matches with a match ID lower than this value (optional)
    * @return kotlin.Array<Inline_response_200_15>
    */
    @Suppress("UNCHECKED_CAST")
    fun publicMatchesGet(mmrAscending: kotlin.Int, mmrDescending: kotlin.Int, lessThanMatchId: kotlin.Int) : kotlin.Array<Inline_response_200_15> {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mapOf("mmrAscending" to listOf("$mmrAscending"), "mmrDescending" to listOf("$mmrDescending"), "lessThanMatchId" to listOf("$lessThanMatchId"))
        val localVariableHeaders: kotlin.collections.Map<kotlin.String,kotlin.String> = mapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/publicMatches",
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val response = request<kotlin.Array<Inline_response_200_15>>(
            localVariableConfig,
            localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<Inline_response_200_15>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
            else -> throw kotlin.IllegalStateException("Undefined ResponseType.")
        }
    }

}
